//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        public int Id { get; set; }
        public double Total_Price { get; set; }

        [Required(ErrorMessage = "*Required")]
        public int Client_id { get; set; }

        [Required(ErrorMessage = "*Required")]
        public int Quentity { get; set; }

        [Required(ErrorMessage = "*Required")]
        public int Item_id { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual item item { get; set; }
    }
}
